### ISSUE TITLE
Sentinel error dropping tables

### ISSUE THREAD

**Issue by mikeytown2** [mikeytown2/masternode#122]
[error] Could not drop tables: database is locked
Traceback (most recent call last):
  File "/home/enrg_mn1/sentinel/bin/sentinel.py", line 9, in <module>
    from models import Superblock, Proposal, GovernanceObject, Watchdog
  File "/home/enrg_mn1/sentinel/lib/models.py", line 821, in <module>
    check_db_sane()     # ensure tables exist
  File "/home/enrg_mn1/sentinel/lib/models.py", line 761, in check_db_sane
    if not getattr(model, 'table_exists')():
  File "/home/enrg_mn1/sentinel/venv/local/lib/python2.7/site-packages/peewee.py", line 4836, in table_exists
    return cls._meta.db_table in cls._meta.database.get_tables(**kwargs)
  File "/home/enrg_mn1/sentinel/venv/local/lib/python2.7/site-packages/peewee.py", line 3893, in get_tables
    'type = ? ORDER BY name;', ('table',))
  File "/home/enrg_mn1/sentinel/venv/local/lib/python2.7/site-packages/peewee.py", line 3683, in execute_sql
    self.commit()
  File "/home/enrg_mn1/sentinel/venv/local/lib/python2.7/site-packages/peewee.py", line 3507, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/enrg_mn1/sentinel/venv/local/lib/python2.7/site-packages/peewee.py", line 3676, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked

**Comment by mikeytown2** [comment]
Might be app armor 
/home/enrg_mn1/sentinel/** mrwk,

**Comment by mikeytown2** [comment]
apparmor updated
